services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway:/gateway
      - /gateway/node_modules
    env_file:
      - ./gateway/.env
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  admin:
    build:
      context: ./services/admin
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/admin:/service/admin
      - ./shared:/service/admin/shared
      - ./services/admin/node_modules:/service/admin/node_modules
    env_file:
      - ./services/admin/.env
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
    command: npm run dev

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth:/service/auth
      - ./services/auth/node_modules:/service/auth/node_modules
    env_file:
      - ./services/auth/.env
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=development
    command: npm run dev
