FROM node:22.18.0-slim

WORKDIR /service/admin

# Install only production dependencies + nodemon globally
COPY services/admin/package*.json ./
RUN npm install


# Copy shared folder into admin folder
COPY shared ./shared

EXPOSE 4001

CMD ["npm", "run", "dev"]
