FROM node:22.18.0-slim

WORKDIR /service/admin

COPY package*.json ./
RUN npm install

COPY start.sh ./

# Give execute permission to start.sh
RUN chmod +x ./start.sh

EXPOSE 4001

# Run start.sh instead of npm run dev directly
CMD ["./start.sh"]
